# Unión de Datos Nuevos

In [49]:
import pandas as pd
from IPython.display import display
import numpy as np
df_0 = pd.read_excel('datos_CAIMEDv8_fixed.xlsx')
df_1 = pd.read_excel('Datos riesgo cardiovascular estudio CARED  para unirv5.xlsx')

In [50]:
df_0['individuo'] = df_0['individuo'].astype(int)
df_1['cedula'] = df_1['cedula'].astype(int)

In [51]:
df_1

,Nombres y apellidos,cedula,edad,ciudad,sexo,Diabetico,Tiempo de DM,Hipertensión,Hipercolesterolemia familiar,ERCoDialisis,Ultimo Rango de Colesterol total,Enfermedad relevante,Infarto agudo al miocardio,ACV,Enf Arterial,Angina Inestable,Angina Estble,Cateterismo cardiaco,Enfermedad arterial periférica,Riesgo CV
0,Yolima Dueñas Albarracin,47427055,61,YOPAL,Femenino,No,NaN,Si,Si,No,Desconocido,Si,No,No,No,No,No,Si,No,Muy alto
1,Gustavo Barona,6301768,66,IBAGUE,Masculino,No,NaN,Si,No,No,Desconocido,Si,Si,No,No,No,No,Si,No,Muy alto
2,David Rivas Barragan,2374303,73,IBAGUE,Masculino,No,NaN,Si,No,No,Desconocido,Si,Si,No,No,No,No,No,No,Muy alto
3,Alejandro Palma,2315455,93,IBAGUE,Masculino,Si,Entre 10 y 20 años,Si,No,No,Desconocido,Si,Si,No,No,No,No,No,No,Muy alto
4,Jorge Salazar,14319350,55,IBAGUE,Masculino,No,NaN,Si,No,No,Desconocido,Si,Si,No,No,No,No,No,No,Muy alto
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
969,OLGA AMELIA TRUJILLO VELANDIA,47425710,54 AÑOS,YOPAL,FEMENINO,Si,NaN,Si,No,No,NA,Si,Si,No,No,No,No,No,No,Muy alto
970,CELIA PEREZ RODRIGUEZ,23738879,81 AÑOS,YOPAL,FEMENINO,No,NaN,Si,No,No,NaN,Si,Si,No,No,No,No,No,No,Muy alto
971,JOSE NICANOR SIGUA GUALDRON,1167028,78 AÑOS,YOPAL,MASCULINO,No,NaN,Si,No,No,NA,Si,Si,No,No,No,No,No,No,Muy alto
972,MIGUEL ANGEL ZERPA LORETO,5614392,55 AÑOS,YOPAL,MASCULINO,No,NaN,Si,No,No,NA,Si,Si,No,No,No,No,No,No,Muy alto
973,NANCY MERCEDES MORALES PARADA,23709564,64 AÑOS,YOPAL,FEMENINO,Si,NaN,Si,No,No,NaN,Si,No,Si,No,No,No,No,No,Muy alto

In [52]:
i = 0
for ced in df_1['cedula']:
    if ced not in list(df_0['individuo'].astype(int)):
        i += 1
        print('eroor', ced)

print(i, 'en total')
i = 0

for ced in df_0['individuo']:
    if ced not in list(df_1['cedula'].astype(int)):
        i += 1
        print('eroor', ced)
print(i, 'en total')

eroor 7530382
eroor 17412049
eroor 22229512
eroor 41783045
eroor 6504609
eroor 65496684
eroor 40315034
eroor 28837359
eroor 38233613
eroor 28814071
eroor 79245518
eroor 18435275
eroor 15895374
eroor 69061001
eroor 24477337
eroor 79314863
eroor 20438765
eroor 17591769
eroor 3297269
eroor 19252859
eroor 23738879
21 en total
eroor 37248444
eroor 30342416
eroor 41785312
eroor 41492534
eroor 79238531
eroor 19069768
eroor 7222256
eroor 4270281
eroor 3271188
eroor 79299980
eroor 79525275
eroor 17412133
eroor 17417296
eroor 17169684
eroor 7767013
eroor 17303472
eroor 41348135
eroor 17308717
eroor 2229512
eroor 93382685
eroor 79061001
eroor 24477837
eroor 7498292
eroor 7562813
eroor 7526706
eroor 25017612
eroor 70380727
eroor 4532751
eroor 1393582
eroor 25021147
eroor 26570822
eroor 7542868
eroor 7555097
eroor 31289330
34 en total

In [53]:
column_names = list(df_1.columns)

In [54]:
dx= {}
for name in column_names:
    dx[name] = []
for row_a in range(len(df_0)):
    founded = False
    index_founded = None
    current_ced  = (df_0.iloc[row_a])['individuo']
    if current_ced in list(df_1['cedula']):
        for column in column_names:
            if column == 'cedula' :
                dx[column].append(int(str(current_ced).replace('.','')))
            else:
                dx[column].append(  list(df_1[df_1['cedula']==current_ced][column])[0]     )
    else:
        for column in column_names:
            dx[column].append('')

In [55]:
dx = pd.DataFrame(dx)

In [56]:
dx['sexo']

0      Masculino
1       Femenino
2      Masculino
3       Femenino
4      Masculino
         ...
982    Masculino
983     Femenino
984    Masculino
985    Masculino
986     Femenino
Name: sexo, Length: 987, dtype: object

In [57]:
len(dx) == len(df_0)

True

In [58]:
dx_2= {}
i = 0
aaa = {0:'a',
       1:'b'}
for name in (list(dx.columns) + list(df_0.columns)):
    if 'sexo' == name:
        dx_2[f'{name}_{aaa[i]}'] = []
        i+= 1
    dx_2[name] = []
for index in range(len(df_0)):
    for name in list(df_0.columns):
        if name == 'sexo':
            dx_2['sexo_a'].append((df_0.iloc[index])['sexo'])
        else:
            dx_2[name].append((df_0.iloc[index])[name])
    for name2 in dx.columns:
        if name2 == 'sexo':
            dx_2['sexo_b'].append((dx.iloc[index])['sexo'])
        else:
            dx_2[name2].append((dx.iloc[index])[name2])

In [59]:
dx_2['sexo'] = dx_2['sexo_a']

In [60]:
dx2 = pd.DataFrame(dx_2)

In [61]:
# Ensure 'cedula' is of type string
dx2['cedula'] = dx2['cedula'].astype(str)

# Filter rows where 'cedula' is not empty
dx2 = dx2[dx2['cedula'] != '']

# Reset the index if required
dx2.reset_index(drop=True, inplace=True)

In [62]:
dx2

,Nombres y apellidos,cedula,edad,ciudad,sexo_a,sexo,Diabetico,Tiempo de DM,Hipertensión,Hipercolesterolemia familiar,...,sobrepeso,obesidad,perimetro_abdominal_normal,perimetro_abdominal_aumentado,perimetro_abdominal_incremento_sustancial,tension_normal,tension_elevada,tension_alta_nivel_1,tension_alta_nivel_2,tension_crisis_hipertensiva
0,Guillermo Fonnegra,70033505,72,BOGOTA,masculino,masculino,No,NaN,Si,Si,...,si,no,no,si,no,no,no,si,no,no
1,Zully De Moya Garzon,41760470,67,BOGOTA,femenino,femenino,No,NaN,No,No,...,no,no,no,si,no,no,no,si,no,no
2,Omar Luengas Perez,17171452,78,BOGOTA,masculino,masculino,No,NaN,Si,Si,...,no,no,si,no,no,no,no,si,no,no
3,Maira Fernández barraza,1019032057,34,BOGOTA,femenino,femenino,No,NaN,No,No,...,si,no,no,no,si,no,no,no,si,no
4,Francisco Javier Mora,19250084,69,BOGOTA,masculino,masculino,No,NaN,No,No,...,si,no,no,si,no,si,no,no,no,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,Jhon Jairo arrubla arrubla,7561381,52,ARMENIA,masculino,masculino,Si,Entre 10 y 20 años,Si,No,...,si,no,no,no,si,no,no,si,no,no
949,Amparo franco reyes,41899611,67,ARMENIA,femenino,femenino,Si,Menos de 10 años,Si,Si,...,no,si,no,no,si,no,no,si,no,no
950,Gabriel Gonzalez Rivera,19317507,67,ARMENIA,masculino,masculino,Si,Menos de 10 años,No,No,...,si,no,no,si,no,si,no,no,no,no
951,jairo alberto ospina bolaño,4398004,83,ARMENIA,masculino,masculino,No,NaN,Si,Si,...,si,no,no,si,no,no,no,si,no,no
952,maria elena parra sosa,41557614,72,ARMENIA,femenino,femenino,Si,Entre 10 y 20 años,No,No,...,no,si,no,no,si,no,si,no,no,no

In [63]:
for i in dx2 : 
    if '' in i:
        print(i)

Nombres y apellidos
cedula
edad
ciudad
sexo_a
sexo
Diabetico
Tiempo de DM
Hipertensión
Hipercolesterolemia familiar
ERCoDialisis
Ultimo Rango de Colesterol total
Enfermedad  relevante
Infarto agudo al miocardio
ACV
Enf Arterial
Angina Inestable
Angina Estble
Cateterismo cardiaco
Enfermedad arterial periférica
Riesgo CV
individuo
fecha_constetimiento_informado
fecha_de_nacimiento
edad_calculada
estado_civil
sexo_b
lugar_de_nacimiento
lugar_de_procedencia
escolaridad
estrato_socieconomico
tipo_de_afiliacion
¿tiene_seguro_de_salud?
tipo_de_seguro_de_salud
antecedentes_de_tabaquismo
presion_arterial_sistolica
presion_arterial_diastolica
peso(kg)
talla(m)
perimetro_abdominal
IMC
IMC_calculada
antecedentes_en_criterios_de_inclusion
POC_hba1c(%)
colesterol_total(mg/dl)
HDL(mg/dl)
trigliceridos(mg/dl)
cLDL(mg/dl)
¿cLDL_menor_a_70mg/dl?
¿nivel_de_HbA1c_menor_de_5.7_%?_o_¿Nivel_de_HbA1c_menor a_7%_si_el_sujeto_es_diabético?
dosis
fecha_de_inicio
Años
Meses
Dias
tipo_de_ocupacion
dislipidemia
hipertension
cardiopatia isquemica
hiperplasia prostatica
hipotiroidismo
acalasia
infarto de miocardio
tiroides
acne
diabetes mellitus
aneurisma
apnea
esclerosis
fibrilacion
migrana
litiasis
neumonia
glaucoma
estenosis
gastritis
sindrome del colon irritable
insuficiencia cardiaca congestiva
trombosis
nefropatia
artrosis
gota
higado graso
bloqueo
hipercolesterolemia
diverticulosis
reflujo
depresion
leucemia
sindrome neuropatico
alzheimer
accidente cerebrovascular
sepsis
queratosis
leucoencefalopatia
angiopatia
esplenectomia
rinitis
vertigo
tumor
poliposis
fascicular
epilepsia
arritmia
osteopenia
valvula
mioclonias
herpes
varicocele
asthma
trastorno
anemia
mieloma
hepatitis
¿hay_antecedentes_familiares?
¿tiene_antecedentes_con_abuelo?
tipo_de_antecedentes_con_abuelo
¿tiene_antecedentes_con_abuela?
tipo_de_antecedentes_con_abuela
¿tiene_antecedentes_con_padre?
tipo_de_antecedentes_con_padre
¿tiene_antecedentes_con_madre?
tipo_de_antecedentes_con_madre
¿tiene_antecedentes_con_herman?
tipo_de_antecedentes_con_herman
¿tiene_antecedentes_con_tio?
tipo_de_antecedentes_con_tio
fumador
tiempo_fumador
bebedor
tiempo_bebedor
otro_antecedente_toxicologico
tiempo_otro_antecedente_toxicologico
Ezetimibe
Degludec
Atorvastatina
Glulisina
Dapagliflozina
Colestiramina
Evolocumab
Glargina
Insulina Glargina
Acido fenofibrico
Fenofibrato
Empagliflozina
Insulina
alirocumab
Dulaglutida
Lantus
Insulina Lispro
Glibenclamida
Glimepirida
Hipolipemiante
Antidiabético
¿se_hizo_examen?
¿resultados_relacionados_a_obesidad?
¿son_signficativos_relacionado_a_obesidad?
¿resultados_relacionados_a_problemas cardiacos?
¿son_signficativos_relacionado_a_problemas cardiacos?
¿resultados_relacionados_a_tension arterial?
¿son_signficativos_relacionado_a_tension arterial?
¿resultados_relacionados_a_accidente cerebrovascular?
¿son_signficativos_relacionado_a_accidente cerebrovascular?
no_diabeticos_POC_hba1c(%)_controlado
diabeticos_POC_hba1c(%)_controlado
bajo_peso
normo_peso
sobrepeso
obesidad
perimetro_abdominal_normal
perimetro_abdominal_aumentado
perimetro_abdominal_incremento_sustancial
tension_normal
tension_elevada
tension_alta_nivel_1
tension_alta_nivel_2
tension_crisis_hipertensiva

In [64]:
display(dx2[dx2['cedula']==79314863])

Empty DataFrame
Columns: [Nombres y apellidos, cedula, edad, ciudad, sexo_a, sexo, Diabetico, Tiempo de DM, Hipertensión , Hipercolesterolemia familiar, ERCoDialisis, Ultimo Rango de Colesterol total, Enfermedad  relevante, Infarto agudo al miocardio, ACV, Enf Arterial, Angina Inestable, Angina Estble, Cateterismo cardiaco, Enfermedad arterial periférica, Riesgo CV, individuo, fecha_constetimiento_informado, fecha_de_nacimiento, edad_calculada, estado_civil, sexo_b, lugar_de_nacimiento, lugar_de_procedencia, escolaridad, estrato_socieconomico, tipo_de_afiliacion, ¿tiene_seguro_de_salud?, tipo_de_seguro_de_salud, antecedentes_de_tabaquismo, presion_arterial_sistolica, presion_arterial_diastolica, peso(kg), talla(m), perimetro_abdominal, IMC, IMC_calculada, antecedentes_en_criterios_de_inclusion, POC_hba1c(%), colesterol_total(mg/dl), HDL(mg/dl), trigliceridos(mg/dl), cLDL(mg/dl), ¿cLDL_menor_a_70mg/dl?, ¿nivel_de_HbA1c_menor_de_5.7_%?_o_¿Nivel_de_HbA1c_menor a_7%_si_el_sujeto_es_diabético?, dosis, fecha_de_inicio, Años, Meses, Dias, tipo_de_ocupacion, dislipidemia, hipertension, cardiopatia isquemica, hiperplasia prostatica, hipotiroidismo, acalasia, infarto de miocardio, tiroides, acne, diabetes mellitus, aneurisma, apnea, esclerosis, fibrilacion, migrana, litiasis, neumonia, glaucoma, estenosis, gastritis, sindrome del colon irritable, insuficiencia cardiaca congestiva, trombosis, nefropatia, artrosis, gota, higado graso, bloqueo, hipercolesterolemia, diverticulosis, reflujo, depresion, leucemia, sindrome neuropatico, alzheimer, accidente cerebrovascular, sepsis, queratosis, leucoencefalopatia, angiopatia, esplenectomia, rinitis, vertigo, tumor, ...]
Index: []

[0 rows x 177 columns]

In [65]:
dx2.to_excel('datos_CAIMEDv8_unido_v2.xlsx',index=False)

In [67]:
for index,i in enumerate(dx2):
    if 'pres' in i:
        print(i,index)

presion_arterial_sistolica 35
presion_arterial_diastolica 36
depresion 87